apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    newrelic.ini: ENC[AES256_GCM,data:39lYVD/7L5JP3YZ+ZMMgKI/LrvUkrAbjjuvAvqYnCO/TKVsEVMo6jCWhenbyr8W2k9Ct1SikgV2f71OWfK4mY0w03JgQYIjLdLPHrianzXEP/Jgf8LApvJUPOcm0D003CNTd8ehDpFK3T824BXWj2iBdQCx1Dmm00iEzEHPrJVtaqFQvSqQ1PLl62X5j2plmvr2WKq0beUAw4gDmx4OMmwPiynW3rnTRYT3jwgsn6IN9AGjZNt2VkxfyYroL4/FeJR+Fp/jO0HfNRskTsu9tDsa0pQUEADzXnUr8Alo92xqAIr9R2JzOiTBTYDaCTIeXpQKe2EqoozSIhUyIe9yfXf34QNYvwa2M/hGyYXqR7JZAVZJfv4+1NdCoDuxY/kh+j6GhwCI+zxmp6Pi8nzB/FtRzdiCxChbgv6jcOoD0bAJjivOCcq1yj2v1g5aImGc1rwhVg+NTIYWU0K4BTq/GUk5L13pl5aqsMS8nCZJJBsQocPL2Dh7cciah6wGvAKBwMBokRhPaKVIfdf60PNw7lQHt5eAB,iv:RDGOGUd499KoHqzCAfGIVA4lVoAnJZ/vQ5YJAK+lGBM=,tag:n1N7w2gh07nY44Gc7VPzbw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2026-07-24T21:08:54Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQGxc5ZHrBcMAECaUyQCBb01AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/1mkGQkGdsJM83ynAgEQgDvdOFds56TVT31GB7nHDTnqnIp27DR8mxRgI0nnkZVXFajUqABLYelWW6CNI6fLv45TWz2rYQsNEna35Q==
          aws_profile: ""
    lastmodified: "2026-07-24T21:08:54Z"
    mac: ENC[AES256_GCM,data:KkyukEk8BPzkSxlK0xxHeraXqlp9RYRmedM4IDXSEpTmw2/GuBF4Coz1QZSUdQNYmePOWGcj5om6oDBsGHXNg92Irx4Pd5U3c/pM5eoR9QZFH9olJ8LhD6MJTlG61JKcwO7/qmnvrWuG0fBoVv7rkHu3feF5PYH3BwBTmySZvyQ=,iv:h90Zo/h4PwkMjUo4i6OiW6KJRPB0aHcQAdIMzkVcXYE=,tag:awDQSZSBW2p+ruGOBMSWMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
