apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

commonLabels:
  env: production

bases:
- ../../base

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ingress-nginx-controller
      namespace: ingress-nginx
    data:
      http-snippet: |
        limit_req_zone $server_name zone=omegaup_problem_global:10m rate=1r/s;
