#cloud-config
package_upgrade: true

packages:
  - xz-utils
  - jq
  - curl
  - gnupg

users:
  - name: omegaup
    homedir: /var/lib/omegaup
    shell: /usr/sbin/nologin

write_files:
  - content: |
      [Unit]
      Description=omegaUp runner
      After=network.target

      [Service]
      Type=simple
      User=omegaup
      Group=omegaup
      PermissionsStartOnly=true
      Delegate=yes
      ExecStartPre=/var/lib/omegajail/bin/omegajail-setup
      ExecStart=/var/lib/omegajail/bin/omegajail-cgroups-wrapper /usr/bin/omegaup-runner
      ExecReload=/bin/kill -s HUP $MAINPID
      WorkingDirectory=/var/lib/omegaup
      Restart=always

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/omegaup-runner.service
    permissions: '0644'
    owner: root:root

  - content: |
      @INCLUDE newrelic_output.conf

      [SERVICE]
          Daemon       Off
          Parsers_File parsers.conf
          Plugins_File plugins.conf

      [INPUT]
          Name           systemd
          Tag            host.*
          Systemd_Filter _SYSTEMD_UNIT=omegaup-runner.service

      [FILTER]
          Name         parser
          Match        *
          Parser       json
          Key_Name     MESSAGE
          Reserve_Data Off
          Preserve_Key Off
    path: /etc/fluent-bit/fluent-bit.conf
    permissions: '0644'
    owner: root:root

  - content: |
      [OUTPUT]
          Name         stdout
          Match        *
    path: /etc/fluent-bit/newrelic_output.conf
    permissions: '0644'
    owner: root:root

  - content: |
      [PLUGINS]
          Path /lib/fluent-bit/out_newrelic-linux-amd64-1.12.1.so
    path: /etc/fluent-bit/plugins.conf
    permissions: '0644'
    owner: root:root


runcmd:
  - |
    curl -fsSL https://packages.fluentbit.io/fluentbit.key \
      | gpg --dearmor \
      -o /usr/share/keyrings/fluentbit-keyring.gpg

    echo "deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/ubuntu/jammy jammy main" \
      > /etc/apt/sources.list.d/fluent-bit.list

    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      -o Dpkg::Options::="--force-confold" \
      fluent-bit

    # Download all the payloads from GitHub and extract them.
    for url in $(echo "https://github.com/omegaup/omegajail/releases/download/v3.13.1/omegajail-jammy-rootfs-x86_64.tar.xz
    https://github.com/omegaup/omegajail/releases/download/v3.13.1/omegajail-jammy-distrib-x86_64.tar.xz
    https://github.com/omegaup/quark/releases/download/v1.9.77/omegaup-runner.tar.xz"); do
      echo "downloading ${url}..."
      curl --silent --location --url "${url}" | tar xJ -C /
    done

    mkdir -p /lib/fluent-bit

    curl \
      --silent \
      --location \
      --url https://github.com/newrelic/newrelic-fluent-bit-output/releases/download/v1.12.1/out_newrelic-linux-amd64-1.12.1.so \
      --output /lib/fluent-bit/out_newrelic-linux-amd64-1.12.1.so

    # Create the directory layout expected by the runner.
    mkdir -p /etc/omegaup/runner /var/log/omegaup /var/lib/omegaup
    chown -R omegaup:omegaup /etc/omegaup /var/log/omegaup /var/lib/omegaup

    /bin/systemctl daemon-reload
    /bin/systemctl enable fluent-bit
    /bin/systemctl enable omegaup-runner

power_state:
    mode: poweroff
    timeout: 30
    condition: True
