apiVersion: v1
kind: Secret
metadata:
    name: fluent-bit-newrelic-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    license-key: ENC[AES256_GCM,data:TY4QcrRQRUCOdb0Z64Pd/e6pS4RyDcezNhZiaClyrDmCYZveQsahkA==,iv:cHwUgnN9KQvkZDtovTRXtVC8bpFqiV7sRGtCVzWNqNo=,tag:sBSbkWw4ezz+egXCxOYUOg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2026-07-24T21:08:55Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQHyh744v8ZMwP+nUlFl2mUVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNJmb2dap7XI/WybYAgEQgDt+KqmnVzude8NhuUIBp5C8EtW5gIfaAKiDq8rgNWPVoXZo6vQXbuhAgXXmXsGhFhDBV+9Osovhik3RXQ==
          aws_profile: ""
    lastmodified: "2026-07-24T21:08:55Z"
    mac: ENC[AES256_GCM,data:CzxphSl7CW7liR65YeEW4mT5XdmU2m0ADdsTVZtFFGiQ8RE4SpsTeFIvBFWWWvFcUPMEvf0R0m5C+M0w4xJvjO6D0U/4g5mOzjkgFf2wHiRClKTtFM34aUzAvfa4eNTrDqXmQ23GExe602kyMI/gyHz2hQTGXdMl/caudblajF0=,iv:oGSlSOcH13lhyEgown2jqekKuuR7TjupHPSOLeTiwSs=,tag:A0MLSShzv/OxWKJYAzXx+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
