apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-config
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: merge
data:
    output.conf: ENC[AES256_GCM,data:QLHTi2Ui2BYvoBs2qjoOco6ew74vBLcryVf31pXt8UOnm3WUfVs7dyvjv05lNtT05qMvuEARjTl94tw4AAOVFvaRlO/zSngsRiWnIfXZuZ8GWHlmDkg2Cugyo20O0g8TOb0cn3VyX43jya5TT7ax61lxjP6IRjyi8exr6mRQDrvDcZbCdJwJMh7HAvqvydcULRsgavZPpoWkCmf18SDL4QxdXC1TlZARXcTFeEOkKIzxzQVU5/TRUVYgW9/nQGMoWZ3lXs11/EAaQNfhx4Tom4Rp2H/SR4hLZK3zGeSKw0mxO7lzAdtoqNKmJDl0oJiFNAmZyG8voZJn58QwNvJdXJ3s4gJnLb2jBk7YJjYcqgTqxD2F9OnsOKEQyXWbgtuAgfreIwmpE2BaNW9lCDnDn3cZuv6ZMprkNin8knxdl92EFkmjhR0DWPO13k0autu9fsO35acoXOXQXVfJvPMhJ3Ovo/usF6ibpfwVLRATKq71Tn1wsigmBhkEUs3Nr79lzOMlTpTWPkjuB1CAeG1VEz9XdTfqbH4+,iv:YwoVT7mcUUtxJZUxibwdaLQDZ7f9XgynkgSeRYYyFcw=,tag:dNiN81TUDQdeKUnz+exDcA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2026-07-24T21:08:54Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQGc7ZaDvnE6puPHyFJerprIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtXgJT8rNNk1xTctZAgEQgDuBr0WHeDNUkv3FTOWI71Q9M1A5TWTmIQs7m3kpuBktQEp1Bh+TQdU6dajsWX5gJcnHqLFMCFmlOVqN7g==
          aws_profile: ""
    lastmodified: "2026-07-24T21:08:55Z"
    mac: ENC[AES256_GCM,data:Gj60Xk6C10FrYOEwTYvPjlMNHM+3NnEa8A/L7kIH+ZaoFBmcgFUiAICn6NI7gxDQ+vMZ6WvmgHlitSIQAcHJHogT4CIPgJ7QOAuvng0MSC/R0h3adez0LmeNx6TcxEMKqKVd3iZzniP8w1z7HcITQCORHDm8R6WFGM/X00cmYSA=,iv:OG7ikgYFRMFgQkoi61paTjHlXZ1hK+S0VhBuJpInVqg=,tag:zqPgSV+a3t2OrWXT+t5gyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
